# Generated by Django 5.1.2 on 2025-01-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulator",
            name="interval",
            field=models.CharField(max_length=255),
        ),
    ]
